version: '3'
services:
  # Nginx server configuration
  web:
    image: nginx:alpine
    container_name: rest_webserver
    ports:
      - "80:80"
    links:
      - php
    volumes:
      - .:/usr/share/nginx/html
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./logs:/var/log/nginx/

  # Php-fpm configuration
  php:
    image: php:7.3-fpm-alpine
    user: "${UID}:${GID}"
    container_name: rest_php
    volumes:
      - .:/usr/share/nginx/html
